# Day_3_1 Study CNN Pytorch modules
- Deep Learning과 Convolution Neural Network과 관련한 Pytorch modules에 대해 실습

![image.png](http://drive.google.com/uc?id=1xSFMz26Z14rldETZG4nXDPq_ZZKK2ISF)

![image.png](http://drive.google.com/uc?id=13WyqK4RTceUmGKL6_Iwgz_2sShX2pVGC)

![image.png](http://drive.google.com/uc?id=1eBPt8_ZfJrG-PrYMffXb_DpaPRutK9jh)

![image.png](http://drive.google.com/uc?id=1PsSApUabTfSseQMH2vLyZKtx9fMJ6fA1)

## 1) nn.Conv2d
- 2-dim 데이터에 하나의 Convolution layer를 생성
- 필요한 하이퍼파라미터를 설정하면 Convolution layer에 필요한 parameter weight를 자동으로 선언
- `Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')`
### parameters
  - in_channels: 입력 채널 수. 흑백 이미지일 경우 1, RGB 값을 가진 이미지일 경우 3
  - out_channels: 출력 채널 수
  - kernel_size: 커널 사이즈
  - stride: stride 사이즈
  - padding: padding 사이즈
### shape
1. Input tensor($N, C_{in}, H_{in}, W_{in}$)
 - $N$: batch의 크기
 - $C_{in}$ : `in_channerls`에 넣은 값과 일치해야 함.
 - $H_{in}$ : 2D input tensor의 높이
 - $ W_{in}$:  2D input tensor의 너비


- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html)

![image.png](http://drive.google.com/uc?id=18ZaNZcwh4SOBSa8WmXtGgQM4iDi6q6F5)

In [2]:
import torch
import torch.nn as nn

### Example 1) kernel_size=3, stride=1, padding=0
![image.png](http://drive.google.com/uc?id=1dvnKVDptCOD1VLtiiTztOB2Lp4SAkuOE)

In [ ]:
input = torch.ones(1,1,4,4)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


### Example 2) kernel_size=3, stride=2, padding=0
![image.png](http://drive.google.com/uc?id=1SgTHZ4mGkQgaHmpVNi-IcHqP1pW5Crm0)

In [ ]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


### Example 3) kernel_size=4, stride=1, padding=2
![image.png](http://drive.google.com/uc?id=1jA5h5lM6mbMtRtBT8rRFacf6yQazmHzW)


In [ ]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=4, stride=1, padding=2)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 6, 6])


### Excercise 1) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1uAgXHskAXGtdowxGKw99Dtw4n4f_X34s)


In [ ]:
input = torch.ones(1,1,6,6)
########################################## Complete This Code~!
in_channels=None
out_channels=None
kernel_size=None
stride=None
padding=None
conv_layer = nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 3, 3])


### Excercise 2) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1Q2WLIYER2T5h8Pri9diRs3J_Kmjb7MXo)


In [ ]:
input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
in_channels=None
out_channels=None
kernel_size=None
stride=None
padding=None
conv_layer = nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 5, 5])


### Excercise 3) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=15MRDXon_68pySZHQy9wBqdbwp8HQNdv8)


In [ ]:
input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
in_channels=None
out_channels=None
kernel_size=None
stride=None
padding=None
conv_layer = nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 3, 3])


### Excercise 4) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=17yCuQSaW2Q0XUwwHG8tBvts15Y-U3we1)

In [ ]:
input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
in_channels=None
out_channels=None
kernel_size=None
stride=None
padding=None
conv_layer = nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 7, 7])


### Excercise 5) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1fNZTyHOtHX0y7sFW-e6tx0qP8mrQ7wK8)

In [ ]:
input = torch.ones(1,3,5,5)
########################################## Complete This Code~!
in_channels=None
out_channels=None
kernel_size=None
stride=None
padding=None
conv_layer = nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 2, 3, 3])


### Excercise 6) Input size=(7,7), kernel_size=3, stride=2, padding=0, Output size=?
![image.png](http://drive.google.com/uc?id=1d9C1FkXHRwx86OfBZ2-1XrIVyak_skMG)

In [ ]:
input = torch.ones(1,1,6,6)
########################################## Complete This Code~!
in_channels=None
out_channels=None
kernel_size=None
stride=None
padding=None
conv_layer = nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


## < Convolution output feature map size 계산 >
![image.png](http://drive.google.com/uc?id=12reHf9xtapZrVBG4LlNbNGa37ZeFfUqk)
![image.png](http://drive.google.com/uc?id=1iqd-9-hHgnc6Zz7kR6v9EMhLWrMmY07N)

In [ ]:
# 예제 1)
########################################## Complete This Code~!
ans_1 = int( (227 - 11 + 2*0) / 4 + 1 )
########################################## Complete This Code~!
print(f'예제 1 정답 : {ans_1}')

# 예제 2)
ans_2 = int( (64 - 7 + 2*0) / 2 + 1 )
print(f'예제 2 정답 : {ans_2}') # 28.5 + 1 => 29

# 예제 3)
########################################## Complete This Code~!
ans_3 = int( (32 - 5 + 2*2) / 1 + 1 )
########################################## Complete This Code~!
print(f'예제 3 정답 : {ans_3}')

# 예제 4)
# <Height>
ans_4_height = int( (32 - 5 + 2*0) / 1 + 1 )
# <Width>
ans_4_width = int( (64 - 5 + 2*0) / 1 + 1 )
print(f'예제 4 정답 : ({ans_4_height}, {ans_4_width})') # (28, 60)

# 예제 5)
# <Height>
########################################## Complete This Code~!
ans_5_height = int((64 - 3 + 2 * 1) + 1)
########################################## Complete This Code~!
#<Width>
########################################## Complete This Code~!
ans_5_width = int((32 - 3 + 2 * 1) + 1)
########################################## Complete This Code~!
print(f'예제 5 정답 : ({ans_5_height}, {ans_5_width})')

예제 1 정답 : 55
예제 2 정답 : 29
예제 3 정답 : 32
예제 4 정답 : (28, 60)
예제 5 정답 : (64, 32)


In [ ]:
# 각 예제에 맞게 INPUT 값을 바꾸어 설정할 수 있습니다.
INPUT_SIZE = (227,227)
IN_CHANNELS = 3
OUT_CHANNELS = 10
KERNEL_SIZE = 11
STRIDE = 4
PADDING = 0

input = torch.ones(1,IN_CHANNELS,INPUT_SIZE[0],INPUT_SIZE[1])
func = nn.Conv2d(in_channels=IN_CHANNELS, out_channels=OUT_CHANNELS, kernel_size=KERNEL_SIZE, stride=STRIDE, padding=PADDING)
output = func(input)
print(output.shape)

torch.Size([1, 10, 55, 55])


## 2) nn.MaxPool2d

- Patch 내에서 가장 두드러진 feature를 추출.
- 모델이 중요한 feature에만 집중할 수 있도록 함. (나머지는 무시)

- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html)

![image.png](http://drive.google.com/uc?id=1010fN_7lMHuxmda3_gdSxfbW36yTC6F5)
![image.png](http://drive.google.com/uc?id=1D2e9iFzJZMPLxRYucC4LS2B44-a3dlQk)

![image.png](http://drive.google.com/uc?id=1xEmoXL-lmanXO6eSYDEmq7_cyFB73dRF)

In [3]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]])
print(input)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])


In [6]:
func = nn.MaxPool2d(kernel_size=2)
output = func(input)
print(output)

tensor([[[6., 8.],
         [3., 4.]]])


## 3) nn.AvgPool2d

- Patch 내의 feature들을 균형있게(balanced) 추출하는 방식
- 정보 손실이 적어 detail을 놓치지 않을 수 있음 (중요하거나/하지 않거나 하는 정보를 구별하지 못하게 됨)


- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.AvgPool2d.html)

![image.png](http://drive.google.com/uc?id=1z4OjHBduieJQVJqquISgrsmVqlVlfgS1)
![image.png](http://drive.google.com/uc?id=10U4Z4OGKSWQHeDMa-f9KRnUXhfGKhKnk)

![image.png](http://drive.google.com/uc?id=1wg2vJ8t780P6l5EUw1oLF3QTSjZBse0a)


In [5]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]])
print(input)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])


In [7]:
func = nn.AvgPool2d(kernel_size=4)
output = func(input)
print(output)

tensor([[[2.7500]]])


## 4) nn.AdaptiveAvgPool2d()
- kernel_size, stride, padding을 입력하는 대신에 output의 사이즈를 입력
-  위의 식에 따라서 자동으로 kernel_size, stride, padding이 결정되어 pooling을 할 수 있음.
- 즉, Average Pooling을 할 때, 출력 크기 조절하기가 상당히 쉬워짐

- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveAvgPool2d.html)

![image.png](http://drive.google.com/uc?id=190yR-M7yTb6ZlILOi4J5RSrfLeh_iul8)

![image.png](http://drive.google.com/uc?id=1KMgjceD4tsS67kUvAb1BYC29HXWJb0Hr)


In [9]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]]) # shpae : [1,4,4]
print(input)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])


In [ ]:
func = nn.AdaptiveAvgPool2d(1) # (1, 1)
output = func(input)
print(output) # shape : [1,1,1]

tensor([[[2.7500]]])


In [8]:
func = nn.AdaptiveAvgPool2d(2) # (2, 2)
output = func(input)
print(output) # shape : [1,2,2]

tensor([[[2.7500, 4.7500],
         [1.7500, 1.7500]]])


In [ ]:
# input channel = 3인 경우
input = torch.randn((1,3,4,4))
print(input)

tensor([[[[ 0.7883, -0.9139, -2.3117,  0.5276],
          [ 0.8452, -2.9044,  1.2648,  1.5481],
          [-0.5473, -0.2154,  0.4562,  0.8117],
          [-0.6663, -1.1137, -0.5429,  1.2258]],

         [[-0.3522, -0.2055, -0.5270, -0.2399],
          [ 0.8420,  0.1785, -0.2320,  1.0298],
          [-1.0613,  0.8084,  1.1157, -0.5487],
          [-0.4375,  0.1039, -1.6958, -0.6947]],

         [[ 0.2658,  0.0365, -0.4793, -0.6779],
          [ 0.3146,  1.1199, -0.6147, -0.9724],
          [ 0.7409, -0.2682, -1.3775, -1.3753],
          [-2.8159,  0.3868,  0.6530, -0.5435]]]])


In [ ]:
func = nn.AdaptiveAvgPool2d(1)
output = func(input)
print(output) # shape : [1,3,1,1]

tensor([[[[-0.1092]],

         [[-0.1198]],

         [[-0.3505]]]])


In [11]:
input = torch.randn((1,3,1,1))
print(input)

tensor([[[[-0.2497]],

         [[ 0.6585]],

         [[-1.3173]]]])


In [12]:
# input size보다 output size가 더 큰 경우

func = nn.AdaptiveAvgPool2d(7) # (7, 7)
output = func(input)
print(output) # shape : [1,3,7,7]

tensor([[[[-0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497],
          [-0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497],
          [-0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497],
          [-0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497],
          [-0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497],
          [-0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497],
          [-0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497, -0.2497]],

         [[ 0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585],
          [ 0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585],
          [ 0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585],
          [ 0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585],
          [ 0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585],
          [ 0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585,  0.6585],
          [ 0.6585,  0.